<?php

//require_once dirname(__FILE__) . '/../../../application/models/CalendarGroupAbstract.php';

/**
 * Test class for Application_Model_CalendarGroupAbstract.
 * Generated by PHPUnit on 2011-11-10 at 19:22:58.
 */
class Application_Model_CalendarGroupAbstractTest extends PHPUnit_Framework_TestCase {

   /**
    * @var Application_Model_CalendarGroupAbstract
    */
   protected $object;

   /**
    * Sets up the fixture, for example, opens a network connection.
    * This method is called before a test is executed.
    */
   protected function setUp() {
      $this->object = new Application_Model_CalendarGroupAbstract;
   }

   /**
    * Tears down the fixture, for example, closes a network connection.
    * This method is called after a test is executed.
    */
   protected function tearDown() {
      
   }

}

?>
