<?php

//require_once dirname(__FILE__) . '/../../../application/models/ReoccurenceTemplate.php';
//require_once dirname(__FILE__) . '/../../../application/models/CalendarGroupInterface.php';
//require_once dirname(__FILE__) . '/../../../application/models/CalendarGroupAbstract.php';
//require_once dirname(__FILE__) . '/../../../application/models/Newsletter.php';

/**
 * Test class for Application_Model_Newsletter.
 * Generated by PHPUnit on 2011-11-10 at 23:16:44.
 */
class Application_Model_NewsletterTest extends PHPUnit_Framework_TestCase {

   /**
    * @var Application_Model_Newsletter
    */
   protected $object;

   /**
    * Sets up the fixture, for example, opens a network connection.
    * This method is called before a test is executed.
    */
   protected function setUp() {
      $this->object = new Application_Model_Newsletter;
   }

   /**
    * Tears down the fixture, for example, closes a network connection.
    * This method is called after a test is executed.
    */
   protected function tearDown() {
      
   }

   public function testGetEntries() {
      $date = new DateTime('2011-11-09');
      $this->assertEquals($date->getTimestamp(), $this->object->getEntries(2011, 11)->getTimestamp());
   }

}

?>
